# Generated by Django 2.2 on 2020-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20200224_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
