# Generated by Django 2.2 on 2020-02-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20200224_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='list_name',
        ),
    ]
