# Generated by Django 2.2 on 2020-02-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20200224_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
