# Generated by Django 2.2 on 2020-02-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20200224_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list_name',
            new_name='list_parent',
        ),
    ]
