# Generated by Django 2.2 on 2020-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20200224_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list_parent',
            field=models.ForeignKey(default=None, on_delete=None, to='lists.List'),
        ),
    ]
