# Generated by Django 2.2 on 2020-02-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_auto_20200224_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list_parent',
            new_name='list',
        ),
    ]
